# Generated by Django 2.1.5 on 2019-01-15 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190115_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 7, 7, 28, 623180, tzinfo=utc)),
        ),
    ]
