# Generated by Django 2.1.5 on 2019-01-15 07:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190115_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 7, 12, 5, 508443, tzinfo=utc)),
        ),
    ]
